//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAPI_tgve
{
    using System;
    using System.Collections.Generic;
    
    public partial class Booking
    {
        public System.DateTime bookingDate { get; set; }
        public decimal bookingPayment { get; set; }
        public int clientId { get; set; }
        public int tourId { get; set; }
        public string eventMonth { get; set; }
        public int eventDay { get; set; }
        public int eventYear { get; set; }
    
        public virtual TourEvent TourEvent { get; set; }
        public virtual Client Client { get; set; }
    }
}
