//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAPI_tgve
{
    using System;
    using System.Collections.Generic;
    
    public partial class Log
    {
        public string OrigAcct { get; set; }
        public System.DateTime LogDateTime { get; set; }
        public string RecAcct { get; set; }
        public decimal Amount { get; set; }
    
        public virtual Account Account { get; set; }
        public virtual Account Account1 { get; set; }
    }
}
