//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAPI_tgve
{
    using System;
    using System.Collections.Generic;
    
    public partial class MOVIE
    {
        public int MOVIENO { get; set; }
        public string TITLE { get; set; }
        public Nullable<short> RELYEAR { get; set; }
        public Nullable<short> RUNTIME { get; set; }
        public string RATINGCODE { get; set; }
        public string COLOURCODE { get; set; }
        public Nullable<decimal> TMDB_SCORE { get; set; }
        public Nullable<decimal> TMDB_VOTES { get; set; }
        public string TMDB_ID { get; set; }
    
        public virtual COLOURTYPE COLOURTYPE { get; set; }
        public virtual RATING RATING { get; set; }
    }
}
