//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAPI_tgve
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order
    {
        public string OrderDate { get; set; }
        public int Quantity { get; set; }
        public string ShipDate { get; set; }
        public string ProductId { get; set; }
        public string CustId { get; set; }
        public string ShipMode { get; set; }
    
        public virtual Customer Customer { get; set; }
        public virtual Product Product { get; set; }
        public virtual Shipping Shipping { get; set; }
    }
}
